// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA91K58o9P1iqN2gEUnffQHy4Ef54nPfwI',
    appId: '1:691204011777:web:ee4597d2655e7d818ecd00',
    messagingSenderId: '691204011777',
    projectId: 'zenlyapp',
    authDomain: 'zenlyapp.firebaseapp.com',
    storageBucket: 'zenlyapp.appspot.com',
    measurementId: 'G-CGJCR8M5TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5KOPIMQYH2vLP7llU6Nbt-c6EZ_WIIGM',
    appId: '1:691204011777:android:f6c5c1e6c2ef23028ecd00',
    messagingSenderId: '691204011777',
    projectId: 'zenlyapp',
    storageBucket: 'zenlyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfAHO27AoXMGZvvPfLyozB_bhKgciLfn0',
    appId: '1:691204011777:ios:7a73f0bb3be72b0d8ecd00',
    messagingSenderId: '691204011777',
    projectId: 'zenlyapp',
    storageBucket: 'zenlyapp.appspot.com',
    iosClientId: '691204011777-dvl6vfqnec060em690loijmp4k35pipk.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenlyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfAHO27AoXMGZvvPfLyozB_bhKgciLfn0',
    appId: '1:691204011777:ios:ebe889f59bb5a3ba8ecd00',
    messagingSenderId: '691204011777',
    projectId: 'zenlyapp',
    storageBucket: 'zenlyapp.appspot.com',
    iosClientId: '691204011777-mns6ocephqv1fk2echft7vl0jh1lsfm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenlyapp.RunnerTests',
  );
}
